### ISSUE TITLE
Bidding and Cancel issues

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/marketplace#96]
From the cityshop.holaplex.market

**Comment by dandlezzz** [comment]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/5935947/157906328-9f081fda-221b-4baa-bd00-4127e8863c2e.png">

**Comment by kespinola** [comment]
This was due to condition of ah that doesnt deduct more funds from the wallet if already has enough to cover the cost. Its unaware of the other offer out. 

We've adjusted submit offer to always deposit the amount of the offer out of the buyer wallet into escrow this ensures all outstanding offers are potentially executable and the books match up.
